### ISSUE TITLE
Feat : Dark mode 

### ISSUE THREAD

**Issue by yuvrxj-afk** [yuvrxj-afk/PaintBot#6]

**Comment by swarajsahil** [comment]
you also  have to add shimmer ui while loading the website.

**Comment by yuvrxj-afk** [comment]
Yes , We need to.

**Comment by swarajsahil** [comment]
i will do that and remove the loading and add the shimmer loading ui like :- 
![Movies-Skeleton-Loading](https://github.com/yuvrxj-afk/PaintBot/assets/43598028/5f6c10bf-1f18-4428-ad8a-ef05edda280d)

**Comment by swarajsahil** [comment]
i also add dark mode and i also see in issue that you also want to improve navbar and tell me what improvement and features you want to add in navbar

**Comment by yuvrxj-afk** [comment]
Assigning you this! Add them up to the UI.
